name: first workflow
on: workflow_dispatch
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: saying hello
        run: echo"Hello bro"
      - name: saying gobye
        run: echo "Done bye bro"

 
